"""Core types for the LLM-as-a-Judge learning project."""

from .contracts import (
    CRITERIA,
    INPUT_ORDER_POLICY,
    RELIABLE_EXAMPLE_POLICY,
    TASK_DEFINITION,
    BinaryEvaluationResult,
    Criterion,
    CriterionScore,
    Decision,
    EvaluationMode,
    EvaluationInput,
    EvaluationResult,
    ExampleLabel,
    InputOrderPolicy,
    PairwiseDecision,
    PairwiseEvaluationResult,
    ReferencePolicy,
    ReliabilityMetric,
    ReliableExamplePolicy,
    TaskComplexity,
)
from .rubric import (
    ACTIVE_RUBRIC,
    RUBRIC_V1,
    RUBRIC_V2,
    EvaluationRubric,
    ExampleKind,
    PairwiseOutcomeGuide,
    RubricCriterion,
    RubricExample,
)
from .dataset import EvaluationCase, EvaluationDataset, ReviewStatus, load_jsonl
from .prompt_builder import (
    ChatMessage,
    JudgePrompt,
    build_judge_prompt,
    response_schema_for_mode,
    select_examples,
)
from .settings import AzureJudgeSettings, SettingsError
from .azure_client import (
    AzureJudgeClient,
    JudgeClientError,
    RawJudgeResponse,
    TokenUsage,
)
from .response_parser import (
    JudgeRefusalError,
    JudgeResponseValidationError,
    ParsedJudgeResult,
    parse_judge_response,
)

__all__ = [
    "CRITERIA",
    "INPUT_ORDER_POLICY",
    "RELIABLE_EXAMPLE_POLICY",
    "TASK_DEFINITION",
    "BinaryEvaluationResult",
    "Criterion",
    "CriterionScore",
    "Decision",
    "EvaluationMode",
    "EvaluationInput",
    "EvaluationResult",
    "ExampleLabel",
    "InputOrderPolicy",
    "PairwiseDecision",
    "PairwiseEvaluationResult",
    "ReferencePolicy",
    "ReliabilityMetric",
    "ReliableExamplePolicy",
    "TaskComplexity",
    "EvaluationRubric",
    "ACTIVE_RUBRIC",
    "RUBRIC_V1",
    "RUBRIC_V2",
    "ExampleKind",
    "PairwiseOutcomeGuide",
    "RubricCriterion",
    "RubricExample",
    "EvaluationCase",
    "EvaluationDataset",
    "ReviewStatus",
    "load_jsonl",
    "ChatMessage",
    "JudgePrompt",
    "build_judge_prompt",
    "response_schema_for_mode",
    "select_examples",
    "AzureJudgeSettings",
    "SettingsError",
    "AzureJudgeClient",
    "JudgeClientError",
    "RawJudgeResponse",
    "TokenUsage",
    "JudgeRefusalError",
    "JudgeResponseValidationError",
    "ParsedJudgeResult",
    "parse_judge_response",
]
